aws lambda update-function-configuration --function-name=$AWS_FUNCTION_ARN --environment="Variables={\
    SECRETS_MANAGER_API_VERSION=$SECRETS_MANAGER_API_VERSION,\
    SECRETS_MANAGER_REGION=$SECRETS_MANAGER_REGION,\
    SECRETS_MANAGER_SECRET=$PROD_SECRETS_MANAGER_REGION,\
    COOKIE_ALGORITHM=$COOKIE_ALGORITHM,\
    COOKIE_NAME=$COOKIE_NAME,\
    OAUTH_ISSUER=$PROD_OAUTH_ISSUER,\
    OAUTH_AUDIENCE=$PROD_OAUTH_AUDIENCE,\
    OAUTH_ALGORITHM=$OAUTH_ALGORITHM,\
    OAUTH_REQUIRED_CLAIM=$PROD_OAUTH_REQUIRED_CLAIM,\
}"