name: "Deployment"
on: workflow_call

jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Modules
        run: npm install
      - name: Build Package
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build-prod
    env:
      SECRETS_MANAGER_SECRET: ${{ secrets.PROD_SECRETS_MANAGER_SECRET }}
      SECRETS_MANAGER_API_VERSION: ${{ secrets.SECRETS_MANAGER_API_VERSION }}
      SECRETS_MANAGER_REGION: ${{ secrets.SECRETS_MANAGER_REGION }}
      COOKIE_ALGORITHM: ${{ secrets.COOKIE_ALGORITHM }}
      COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
      OAUTH_ISSUER: ${{ secrets.PROD_OAUTH_ISSUER }}
      OAUTH_AUDIENCE: ${{ secrets.PROD_OAUTH_AUDIENCE }}
      OAUTH_ALGORITHM: ${{ secrets.OAUTH_ALGORITHM }}
      OAUTH_REQUIRED_CLAIM: ${{ secrets.PROD_OAUTH_REQUIRED_CLAIM }}
      AWS_FUNCTION_ARN: ${{ secrets.AWS_FUNCTION_ARN }}
      BUILD_ZIP_FILE: ${{ secrets.BUILD_ZIP_FILE }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Configure Deployment Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::145724753995:role/com-schoepproject-authorize-cd
          role-session-name: Github-Actions-Deploy-Lambda
          aws-region: us-east-1
      - name: Upload Environment
        run: bash ./.github/scripts/update-environment.sh
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Upload to Lambda
        run: bash ../.github/scripts/upload-code.sh
        working-directory: build
