name: "Integration"
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  cache: "npm"
            - name: Install Modules
              run: npm install
            - name: Build Package
              run: npm run build
            - name: Archive prod artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            id-token: write
            contents: read
        steps:
            - name: "Configure Deployment Credentials"
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::145724753995:role/com-schoepproject-authorize-cd
                  role-session-name: Github-Actions-Deploy-Lambda
                  aws-region: us-east-1
            - name: Download build
              uses: actions/download-artifact@v3
              with:
                  name: build
                  path: dist
            - name: Upload to Lambda
              run: bash ./.github/scripts/lambda.sh
              working-directory: build
